// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFAOM_z2fUnz7IzDYT123o6DUwDS_wxII',
    appId: '1:282822300640:web:8d1825d7f26f2c8ef7d185',
    messagingSenderId: '282822300640',
    projectId: 'redius-ec442',
    authDomain: 'redius-ec442.firebaseapp.com',
    storageBucket: 'redius-ec442.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrh5aKRgvqt6tEw-fM68HFl3FM5ilWR0',
    appId: '1:282822300640:android:503c9ddfdd8a9f23f7d185',
    messagingSenderId: '282822300640',
    projectId: 'redius-ec442',
    storageBucket: 'redius-ec442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDynKTkKuP--9Ol3uOgucpLN50JvtiY8Z4',
    appId: '1:282822300640:ios:355451c70c9cc9e4f7d185',
    messagingSenderId: '282822300640',
    projectId: 'redius-ec442',
    storageBucket: 'redius-ec442.appspot.com',
    iosBundleId: 'com.example.rediusAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDynKTkKuP--9Ol3uOgucpLN50JvtiY8Z4',
    appId: '1:282822300640:ios:355451c70c9cc9e4f7d185',
    messagingSenderId: '282822300640',
    projectId: 'redius-ec442',
    storageBucket: 'redius-ec442.appspot.com',
    iosBundleId: 'com.example.rediusAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFAOM_z2fUnz7IzDYT123o6DUwDS_wxII',
    appId: '1:282822300640:web:f78c3fbeaf190507f7d185',
    messagingSenderId: '282822300640',
    projectId: 'redius-ec442',
    authDomain: 'redius-ec442.firebaseapp.com',
    storageBucket: 'redius-ec442.appspot.com',
  );
}
